"""Major world cities with IANA timezone strings."""

CITIES = [
    # Africa
    {"city": "Abidjan", "country": "Ivory Coast", "timezone": "Africa/Abidjan"},
    {"city": "Accra", "country": "Ghana", "timezone": "Africa/Accra"},
    {"city": "Addis Ababa", "country": "Ethiopia", "timezone": "Africa/Addis_Ababa"},
    {"city": "Alexandria", "country": "Egypt", "timezone": "Africa/Cairo"},
    {"city": "Algiers", "country": "Algeria", "timezone": "Africa/Algiers"},
    {"city": "Antananarivo", "country": "Madagascar", "timezone": "Indian/Antananarivo"},
    {"city": "Bamako", "country": "Mali", "timezone": "Africa/Bamako"},
    {"city": "Bangui", "country": "Central African Republic", "timezone": "Africa/Bangui"},
    {"city": "Banjul", "country": "Gambia", "timezone": "Africa/Banjul"},
    {"city": "Bissau", "country": "Guinea-Bissau", "timezone": "Africa/Bissau"},
    {"city": "Blantyre", "country": "Malawi", "timezone": "Africa/Blantyre"},
    {"city": "Brazzaville", "country": "Congo", "timezone": "Africa/Brazzaville"},
    {"city": "Bujumbura", "country": "Burundi", "timezone": "Africa/Bujumbura"},
    {"city": "Cairo", "country": "Egypt", "timezone": "Africa/Cairo"},
    {"city": "Cape Town", "country": "South Africa", "timezone": "Africa/Johannesburg"},
    {"city": "Casablanca", "country": "Morocco", "timezone": "Africa/Casablanca"},
    {"city": "Conakry", "country": "Guinea", "timezone": "Africa/Conakry"},
    {"city": "Dakar", "country": "Senegal", "timezone": "Africa/Dakar"},
    {"city": "Dar es Salaam", "country": "Tanzania", "timezone": "Africa/Dar_es_Salaam"},
    {"city": "Djibouti", "country": "Djibouti", "timezone": "Africa/Djibouti"},
    {"city": "Douala", "country": "Cameroon", "timezone": "Africa/Douala"},
    {"city": "Durban", "country": "South Africa", "timezone": "Africa/Johannesburg"},
    {"city": "Freetown", "country": "Sierra Leone", "timezone": "Africa/Freetown"},
    {"city": "Gaborone", "country": "Botswana", "timezone": "Africa/Gaborone"},
    {"city": "Harare", "country": "Zimbabwe", "timezone": "Africa/Harare"},
    {"city": "Johannesburg", "country": "South Africa", "timezone": "Africa/Johannesburg"},
    {"city": "Kampala", "country": "Uganda", "timezone": "Africa/Kampala"},
    {"city": "Khartoum", "country": "Sudan", "timezone": "Africa/Khartoum"},
    {"city": "Kigali", "country": "Rwanda", "timezone": "Africa/Kigali"},
    {"city": "Kinshasa", "country": "DR Congo", "timezone": "Africa/Kinshasa"},
    {"city": "Lagos", "country": "Nigeria", "timezone": "Africa/Lagos"},
    {"city": "Libreville", "country": "Gabon", "timezone": "Africa/Libreville"},
    {"city": "Lilongwe", "country": "Malawi", "timezone": "Africa/Blantyre"},
    {"city": "Lome", "country": "Togo", "timezone": "Africa/Lome"},
    {"city": "Luanda", "country": "Angola", "timezone": "Africa/Luanda"},
    {"city": "Lubumbashi", "country": "DR Congo", "timezone": "Africa/Lubumbashi"},
    {"city": "Lusaka", "country": "Zambia", "timezone": "Africa/Lusaka"},
    {"city": "Malabo", "country": "Equatorial Guinea", "timezone": "Africa/Malabo"},
    {"city": "Maputo", "country": "Mozambique", "timezone": "Africa/Maputo"},
    {"city": "Marrakech", "country": "Morocco", "timezone": "Africa/Casablanca"},
    {"city": "Maseru", "country": "Lesotho", "timezone": "Africa/Maseru"},
    {"city": "Mbabane", "country": "Eswatini", "timezone": "Africa/Mbabane"},
    {"city": "Mogadishu", "country": "Somalia", "timezone": "Africa/Mogadishu"},
    {"city": "Monrovia", "country": "Liberia", "timezone": "Africa/Monrovia"},
    {"city": "Moroni", "country": "Comoros", "timezone": "Indian/Comoro"},
    {"city": "Nairobi", "country": "Kenya", "timezone": "Africa/Nairobi"},
    {"city": "N'Djamena", "country": "Chad", "timezone": "Africa/Ndjamena"},
    {"city": "Niamey", "country": "Niger", "timezone": "Africa/Niamey"},
    {"city": "Nouakchott", "country": "Mauritania", "timezone": "Africa/Nouakchott"},
    {"city": "Ouagadougou", "country": "Burkina Faso", "timezone": "Africa/Ouagadougou"},
    {"city": "Porto-Novo", "country": "Benin", "timezone": "Africa/Porto-Novo"},
    {"city": "Pretoria", "country": "South Africa", "timezone": "Africa/Johannesburg"},
    {"city": "Rabat", "country": "Morocco", "timezone": "Africa/Casablanca"},
    {"city": "Sao Tome", "country": "Sao Tome and Principe", "timezone": "Africa/Sao_Tome"},
    {"city": "Tripoli", "country": "Libya", "timezone": "Africa/Tripoli"},
    {"city": "Tunis", "country": "Tunisia", "timezone": "Africa/Tunis"},
    {"city": "Windhoek", "country": "Namibia", "timezone": "Africa/Windhoek"},
    {"city": "Yamoussoukro", "country": "Ivory Coast", "timezone": "Africa/Abidjan"},
    {"city": "Yaounde", "country": "Cameroon", "timezone": "Africa/Douala"},

    # Americas — North
    {"city": "Atlanta", "country": "United States", "timezone": "America/New_York"},
    {"city": "Austin", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Baltimore", "country": "United States", "timezone": "America/New_York"},
    {"city": "Belmopan", "country": "Belize", "timezone": "America/Belize"},
    {"city": "Boston", "country": "United States", "timezone": "America/New_York"},
    {"city": "Calgary", "country": "Canada", "timezone": "America/Edmonton"},
    {"city": "Charlotte", "country": "United States", "timezone": "America/New_York"},
    {"city": "Chicago", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Columbus", "country": "United States", "timezone": "America/New_York"},
    {"city": "Dallas", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Denver", "country": "United States", "timezone": "America/Denver"},
    {"city": "Detroit", "country": "United States", "timezone": "America/Detroit"},
    {"city": "Edmonton", "country": "Canada", "timezone": "America/Edmonton"},
    {"city": "El Paso", "country": "United States", "timezone": "America/Denver"},
    {"city": "Ft. Worth", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Guadalajara", "country": "Mexico", "timezone": "America/Mexico_City"},
    {"city": "Guatemala City", "country": "Guatemala", "timezone": "America/Guatemala"},
    {"city": "Havana", "country": "Cuba", "timezone": "America/Havana"},
    {"city": "Honolulu", "country": "United States", "timezone": "Pacific/Honolulu"},
    {"city": "Houston", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Indianapolis", "country": "United States", "timezone": "America/Indiana/Indianapolis"},
    {"city": "Jacksonville", "country": "United States", "timezone": "America/New_York"},
    {"city": "Kansas City", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Kingston", "country": "Jamaica", "timezone": "America/Jamaica"},
    {"city": "Las Vegas", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "Los Angeles", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "Managua", "country": "Nicaragua", "timezone": "America/Managua"},
    {"city": "Memphis", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Mexico City", "country": "Mexico", "timezone": "America/Mexico_City"},
    {"city": "Miami", "country": "United States", "timezone": "America/New_York"},
    {"city": "Milwaukee", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Minneapolis", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Monterrey", "country": "Mexico", "timezone": "America/Monterrey"},
    {"city": "Montreal", "country": "Canada", "timezone": "America/Montreal"},
    {"city": "Nassau", "country": "Bahamas", "timezone": "America/Nassau"},
    {"city": "New Orleans", "country": "United States", "timezone": "America/Chicago"},
    {"city": "New York", "country": "United States", "timezone": "America/New_York"},
    {"city": "Oklahoma City", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Ottawa", "country": "Canada", "timezone": "America/Toronto"},
    {"city": "Panama City", "country": "Panama", "timezone": "America/Panama"},
    {"city": "Philadelphia", "country": "United States", "timezone": "America/New_York"},
    {"city": "Phoenix", "country": "United States", "timezone": "America/Phoenix"},
    {"city": "Port-au-Prince", "country": "Haiti", "timezone": "America/Port-au-Prince"},
    {"city": "Portland", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "Puebla", "country": "Mexico", "timezone": "America/Mexico_City"},
    {"city": "Quebec City", "country": "Canada", "timezone": "America/Toronto"},
    {"city": "Raleigh", "country": "United States", "timezone": "America/New_York"},
    {"city": "Sacramento", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "Salt Lake City", "country": "United States", "timezone": "America/Denver"},
    {"city": "San Antonio", "country": "United States", "timezone": "America/Chicago"},
    {"city": "San Diego", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "San Francisco", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "San Jose", "country": "Costa Rica", "timezone": "America/Costa_Rica"},
    {"city": "San Jose", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "San Salvador", "country": "El Salvador", "timezone": "America/El_Salvador"},
    {"city": "Seattle", "country": "United States", "timezone": "America/Los_Angeles"},
    {"city": "St. Louis", "country": "United States", "timezone": "America/Chicago"},
    {"city": "Tampa", "country": "United States", "timezone": "America/New_York"},
    {"city": "Tegucigalpa", "country": "Honduras", "timezone": "America/Tegucigalpa"},
    {"city": "Tijuana", "country": "Mexico", "timezone": "America/Tijuana"},
    {"city": "Toronto", "country": "Canada", "timezone": "America/Toronto"},
    {"city": "Vancouver", "country": "Canada", "timezone": "America/Vancouver"},
    {"city": "Washington DC", "country": "United States", "timezone": "America/New_York"},
    {"city": "Winnipeg", "country": "Canada", "timezone": "America/Winnipeg"},

    # Americas — Caribbean
    {"city": "Bridgetown", "country": "Barbados", "timezone": "America/Barbados"},
    {"city": "Castries", "country": "Saint Lucia", "timezone": "America/St_Lucia"},
    {"city": "Fort-de-France", "country": "Martinique", "timezone": "America/Martinique"},
    {"city": "Georgetown", "country": "Guyana", "timezone": "America/Guyana"},
    {"city": "Paramaribo", "country": "Suriname", "timezone": "America/Paramaribo"},
    {"city": "Port of Spain", "country": "Trinidad and Tobago", "timezone": "America/Port_of_Spain"},
    {"city": "Santo Domingo", "country": "Dominican Republic", "timezone": "America/Santo_Domingo"},

    # Americas — South
    {"city": "Asuncion", "country": "Paraguay", "timezone": "America/Asuncion"},
    {"city": "Barranquilla", "country": "Colombia", "timezone": "America/Bogota"},
    {"city": "Belo Horizonte", "country": "Brazil", "timezone": "America/Sao_Paulo"},
    {"city": "Bogota", "country": "Colombia", "timezone": "America/Bogota"},
    {"city": "Brasilia", "country": "Brazil", "timezone": "America/Sao_Paulo"},
    {"city": "Buenos Aires", "country": "Argentina", "timezone": "America/Argentina/Buenos_Aires"},
    {"city": "Cali", "country": "Colombia", "timezone": "America/Bogota"},
    {"city": "Caracas", "country": "Venezuela", "timezone": "America/Caracas"},
    {"city": "Cartagena", "country": "Colombia", "timezone": "America/Bogota"},
    {"city": "Cordoba", "country": "Argentina", "timezone": "America/Argentina/Cordoba"},
    {"city": "Curitiba", "country": "Brazil", "timezone": "America/Sao_Paulo"},
    {"city": "Fortaleza", "country": "Brazil", "timezone": "America/Fortaleza"},
    {"city": "Guayaquil", "country": "Ecuador", "timezone": "America/Guayaquil"},
    {"city": "La Paz", "country": "Bolivia", "timezone": "America/La_Paz"},
    {"city": "Lima", "country": "Peru", "timezone": "America/Lima"},
    {"city": "Manaus", "country": "Brazil", "timezone": "America/Manaus"},
    {"city": "Medellin", "country": "Colombia", "timezone": "America/Bogota"},
    {"city": "Mendoza", "country": "Argentina", "timezone": "America/Argentina/Mendoza"},
    {"city": "Montevideo", "country": "Uruguay", "timezone": "America/Montevideo"},
    {"city": "Porto Alegre", "country": "Brazil", "timezone": "America/Sao_Paulo"},
    {"city": "Quito", "country": "Ecuador", "timezone": "America/Guayaquil"},
    {"city": "Recife", "country": "Brazil", "timezone": "America/Recife"},
    {"city": "Rio de Janeiro", "country": "Brazil", "timezone": "America/Sao_Paulo"},
    {"city": "Rosario", "country": "Argentina", "timezone": "America/Argentina/Buenos_Aires"},
    {"city": "Salvador", "country": "Brazil", "timezone": "America/Bahia"},
    {"city": "Santiago", "country": "Chile", "timezone": "America/Santiago"},
    {"city": "Sao Paulo", "country": "Brazil", "timezone": "America/Sao_Paulo"},
    {"city": "Sucre", "country": "Bolivia", "timezone": "America/La_Paz"},

    # Asia — Central
    {"city": "Almaty", "country": "Kazakhstan", "timezone": "Asia/Almaty"},
    {"city": "Ashgabat", "country": "Turkmenistan", "timezone": "Asia/Ashgabat"},
    {"city": "Astana", "country": "Kazakhstan", "timezone": "Asia/Almaty"},
    {"city": "Bishkek", "country": "Kyrgyzstan", "timezone": "Asia/Bishkek"},
    {"city": "Dushanbe", "country": "Tajikistan", "timezone": "Asia/Dushanbe"},
    {"city": "Tashkent", "country": "Uzbekistan", "timezone": "Asia/Tashkent"},

    # Asia — East
    {"city": "Beijing", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Chengdu", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Chongqing", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Dongguan", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Guangzhou", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Hangzhou", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Hong Kong", "country": "Hong Kong", "timezone": "Asia/Hong_Kong"},
    {"city": "Nanjing", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Osaka", "country": "Japan", "timezone": "Asia/Tokyo"},
    {"city": "Pyongyang", "country": "North Korea", "timezone": "Asia/Pyongyang"},
    {"city": "Seoul", "country": "South Korea", "timezone": "Asia/Seoul"},
    {"city": "Shanghai", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Shenyang", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Shenzhen", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Taipei", "country": "Taiwan", "timezone": "Asia/Taipei"},
    {"city": "Tianjin", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Tokyo", "country": "Japan", "timezone": "Asia/Tokyo"},
    {"city": "Ulaanbaatar", "country": "Mongolia", "timezone": "Asia/Ulaanbaatar"},
    {"city": "Wuhan", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Xi'an", "country": "China", "timezone": "Asia/Shanghai"},
    {"city": "Yokohama", "country": "Japan", "timezone": "Asia/Tokyo"},

    # Asia — South
    {"city": "Ahmedabad", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Bangalore", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Chennai", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Colombo", "country": "Sri Lanka", "timezone": "Asia/Colombo"},
    {"city": "Dhaka", "country": "Bangladesh", "timezone": "Asia/Dhaka"},
    {"city": "Hyderabad", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Islamabad", "country": "Pakistan", "timezone": "Asia/Karachi"},
    {"city": "Jaipur", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Karachi", "country": "Pakistan", "timezone": "Asia/Karachi"},
    {"city": "Kathmandu", "country": "Nepal", "timezone": "Asia/Kathmandu"},
    {"city": "Kolkata", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Lahore", "country": "Pakistan", "timezone": "Asia/Karachi"},
    {"city": "Male", "country": "Maldives", "timezone": "Indian/Maldives"},
    {"city": "Mumbai", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "New Delhi", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Pune", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Surat", "country": "India", "timezone": "Asia/Kolkata"},
    {"city": "Thimphu", "country": "Bhutan", "timezone": "Asia/Thimphu"},

    # Asia — Southeast
    {"city": "Bandar Seri Begawan", "country": "Brunei", "timezone": "Asia/Brunei"},
    {"city": "Bangkok", "country": "Thailand", "timezone": "Asia/Bangkok"},
    {"city": "Dili", "country": "Timor-Leste", "timezone": "Asia/Dili"},
    {"city": "Hanoi", "country": "Vietnam", "timezone": "Asia/Bangkok"},
    {"city": "Ho Chi Minh City", "country": "Vietnam", "timezone": "Asia/Bangkok"},
    {"city": "Jakarta", "country": "Indonesia", "timezone": "Asia/Jakarta"},
    {"city": "Kuala Lumpur", "country": "Malaysia", "timezone": "Asia/Kuala_Lumpur"},
    {"city": "Makassar", "country": "Indonesia", "timezone": "Asia/Makassar"},
    {"city": "Manila", "country": "Philippines", "timezone": "Asia/Manila"},
    {"city": "Naypyidaw", "country": "Myanmar", "timezone": "Asia/Yangon"},
    {"city": "Phnom Penh", "country": "Cambodia", "timezone": "Asia/Phnom_Penh"},
    {"city": "Singapore", "country": "Singapore", "timezone": "Asia/Singapore"},
    {"city": "Surabaya", "country": "Indonesia", "timezone": "Asia/Jakarta"},
    {"city": "Vientiane", "country": "Laos", "timezone": "Asia/Vientiane"},
    {"city": "Yangon", "country": "Myanmar", "timezone": "Asia/Yangon"},

    # Asia — West / Middle East
    {"city": "Amman", "country": "Jordan", "timezone": "Asia/Amman"},
    {"city": "Ankara", "country": "Turkey", "timezone": "Europe/Istanbul"},
    {"city": "Baghdad", "country": "Iraq", "timezone": "Asia/Baghdad"},
    {"city": "Baku", "country": "Azerbaijan", "timezone": "Asia/Baku"},
    {"city": "Beirut", "country": "Lebanon", "timezone": "Asia/Beirut"},
    {"city": "Damascus", "country": "Syria", "timezone": "Asia/Damascus"},
    {"city": "Doha", "country": "Qatar", "timezone": "Asia/Qatar"},
    {"city": "Dubai", "country": "UAE", "timezone": "Asia/Dubai"},
    {"city": "Gaza", "country": "Palestinian Territory", "timezone": "Asia/Gaza"},
    {"city": "Istanbul", "country": "Turkey", "timezone": "Europe/Istanbul"},
    {"city": "Jerusalem", "country": "Israel", "timezone": "Asia/Jerusalem"},
    {"city": "Kuwait City", "country": "Kuwait", "timezone": "Asia/Kuwait"},
    {"city": "Manama", "country": "Bahrain", "timezone": "Asia/Bahrain"},
    {"city": "Muscat", "country": "Oman", "timezone": "Asia/Muscat"},
    {"city": "Nicosia", "country": "Cyprus", "timezone": "Asia/Nicosia"},
    {"city": "Riyadh", "country": "Saudi Arabia", "timezone": "Asia/Riyadh"},
    {"city": "Sanaa", "country": "Yemen", "timezone": "Asia/Aden"},
    {"city": "Tel Aviv", "country": "Israel", "timezone": "Asia/Jerusalem"},
    {"city": "Tehran", "country": "Iran", "timezone": "Asia/Tehran"},
    {"city": "Tbilisi", "country": "Georgia", "timezone": "Asia/Tbilisi"},
    {"city": "Yerevan", "country": "Armenia", "timezone": "Asia/Yerevan"},

    # Europe — Western
    {"city": "Amsterdam", "country": "Netherlands", "timezone": "Europe/Amsterdam"},
    {"city": "Andorra la Vella", "country": "Andorra", "timezone": "Europe/Andorra"},
    {"city": "Athens", "country": "Greece", "timezone": "Europe/Athens"},
    {"city": "Barcelona", "country": "Spain", "timezone": "Europe/Madrid"},
    {"city": "Berlin", "country": "Germany", "timezone": "Europe/Berlin"},
    {"city": "Bern", "country": "Switzerland", "timezone": "Europe/Zurich"},
    {"city": "Brussels", "country": "Belgium", "timezone": "Europe/Brussels"},
    {"city": "Cologne", "country": "Germany", "timezone": "Europe/Berlin"},
    {"city": "Copenhagen", "country": "Denmark", "timezone": "Europe/Copenhagen"},
    {"city": "Dublin", "country": "Ireland", "timezone": "Europe/Dublin"},
    {"city": "Dusseldorf", "country": "Germany", "timezone": "Europe/Berlin"},
    {"city": "Edinburgh", "country": "United Kingdom", "timezone": "Europe/London"},
    {"city": "Frankfurt", "country": "Germany", "timezone": "Europe/Berlin"},
    {"city": "Geneva", "country": "Switzerland", "timezone": "Europe/Zurich"},
    {"city": "Hamburg", "country": "Germany", "timezone": "Europe/Berlin"},
    {"city": "Helsinki", "country": "Finland", "timezone": "Europe/Helsinki"},
    {"city": "Lisbon", "country": "Portugal", "timezone": "Europe/Lisbon"},
    {"city": "Ljubljana", "country": "Slovenia", "timezone": "Europe/Ljubljana"},
    {"city": "London", "country": "United Kingdom", "timezone": "Europe/London"},
    {"city": "Luxembourg City", "country": "Luxembourg", "timezone": "Europe/Luxembourg"},
    {"city": "Lyon", "country": "France", "timezone": "Europe/Paris"},
    {"city": "Madrid", "country": "Spain", "timezone": "Europe/Madrid"},
    {"city": "Marseille", "country": "France", "timezone": "Europe/Paris"},
    {"city": "Milan", "country": "Italy", "timezone": "Europe/Rome"},
    {"city": "Monaco", "country": "Monaco", "timezone": "Europe/Monaco"},
    {"city": "Munich", "country": "Germany", "timezone": "Europe/Berlin"},
    {"city": "Naples", "country": "Italy", "timezone": "Europe/Rome"},
    {"city": "Oslo", "country": "Norway", "timezone": "Europe/Oslo"},
    {"city": "Palma", "country": "Spain", "timezone": "Europe/Madrid"},
    {"city": "Paris", "country": "France", "timezone": "Europe/Paris"},
    {"city": "Porto", "country": "Portugal", "timezone": "Europe/Lisbon"},
    {"city": "Rome", "country": "Italy", "timezone": "Europe/Rome"},
    {"city": "Rotterdam", "country": "Netherlands", "timezone": "Europe/Amsterdam"},
    {"city": "Seville", "country": "Spain", "timezone": "Europe/Madrid"},
    {"city": "Stockholm", "country": "Sweden", "timezone": "Europe/Stockholm"},
    {"city": "Stuttgart", "country": "Germany", "timezone": "Europe/Berlin"},
    {"city": "Turin", "country": "Italy", "timezone": "Europe/Rome"},
    {"city": "Vaduz", "country": "Liechtenstein", "timezone": "Europe/Vaduz"},
    {"city": "Valencia", "country": "Spain", "timezone": "Europe/Madrid"},
    {"city": "Vatican City", "country": "Vatican", "timezone": "Europe/Vatican"},
    {"city": "Vienna", "country": "Austria", "timezone": "Europe/Vienna"},
    {"city": "Zurich", "country": "Switzerland", "timezone": "Europe/Zurich"},

    # Europe — Eastern & Baltic
    {"city": "Belgrade", "country": "Serbia", "timezone": "Europe/Belgrade"},
    {"city": "Bratislava", "country": "Slovakia", "timezone": "Europe/Bratislava"},
    {"city": "Bucharest", "country": "Romania", "timezone": "Europe/Bucharest"},
    {"city": "Budapest", "country": "Hungary", "timezone": "Europe/Budapest"},
    {"city": "Chisinau", "country": "Moldova", "timezone": "Europe/Chisinau"},
    {"city": "Kyiv", "country": "Ukraine", "timezone": "Europe/Kyiv"},
    {"city": "Minsk", "country": "Belarus", "timezone": "Europe/Minsk"},
    {"city": "Moscow", "country": "Russia", "timezone": "Europe/Moscow"},
    {"city": "Nizhny Novgorod", "country": "Russia", "timezone": "Europe/Moscow"},
    {"city": "Podgorica", "country": "Montenegro", "timezone": "Europe/Podgorica"},
    {"city": "Prague", "country": "Czech Republic", "timezone": "Europe/Prague"},
    {"city": "Pristina", "country": "Kosovo", "timezone": "Europe/Belgrade"},
    {"city": "Riga", "country": "Latvia", "timezone": "Europe/Riga"},
    {"city": "Sarajevo", "country": "Bosnia and Herzegovina", "timezone": "Europe/Sarajevo"},
    {"city": "Skopje", "country": "North Macedonia", "timezone": "Europe/Skopje"},
    {"city": "Sofia", "country": "Bulgaria", "timezone": "Europe/Sofia"},
    {"city": "St. Petersburg", "country": "Russia", "timezone": "Europe/Moscow"},
    {"city": "Tallinn", "country": "Estonia", "timezone": "Europe/Tallinn"},
    {"city": "Tirana", "country": "Albania", "timezone": "Europe/Tirane"},
    {"city": "Vilnius", "country": "Lithuania", "timezone": "Europe/Vilnius"},
    {"city": "Warsaw", "country": "Poland", "timezone": "Europe/Warsaw"},
    {"city": "Zagreb", "country": "Croatia", "timezone": "Europe/Zagreb"},

    # Europe — Nordic / North Atlantic
    {"city": "Nuuk", "country": "Greenland", "timezone": "America/Nuuk"},
    {"city": "Reykjavik", "country": "Iceland", "timezone": "Atlantic/Reykjavik"},
    {"city": "Torshavn", "country": "Faroe Islands", "timezone": "Atlantic/Faroe"},

    # Oceania
    {"city": "Adelaide", "country": "Australia", "timezone": "Australia/Adelaide"},
    {"city": "Auckland", "country": "New Zealand", "timezone": "Pacific/Auckland"},
    {"city": "Brisbane", "country": "Australia", "timezone": "Australia/Brisbane"},
    {"city": "Canberra", "country": "Australia", "timezone": "Australia/Sydney"},
    {"city": "Christchurch", "country": "New Zealand", "timezone": "Pacific/Auckland"},
    {"city": "Darwin", "country": "Australia", "timezone": "Australia/Darwin"},
    {"city": "Hobart", "country": "Australia", "timezone": "Australia/Hobart"},
    {"city": "Melbourne", "country": "Australia", "timezone": "Australia/Melbourne"},
    {"city": "Noumea", "country": "New Caledonia", "timezone": "Pacific/Noumea"},
    {"city": "Papeete", "country": "French Polynesia", "timezone": "Pacific/Tahiti"},
    {"city": "Perth", "country": "Australia", "timezone": "Australia/Perth"},
    {"city": "Port Moresby", "country": "Papua New Guinea", "timezone": "Pacific/Port_Moresby"},
    {"city": "Port Vila", "country": "Vanuatu", "timezone": "Pacific/Efate"},
    {"city": "Suva", "country": "Fiji", "timezone": "Pacific/Fiji"},
    {"city": "Sydney", "country": "Australia", "timezone": "Australia/Sydney"},
    {"city": "Wellington", "country": "New Zealand", "timezone": "Pacific/Auckland"},
]
